### ISSUE TITLE
Can't change author when in subdirectory

### ISSUE THREAD

**Issue by himynameisjonas** [teoljungberg/git-duo#3]
Seems like it doesn't work if commands are executed in a sub directory inside the git repo

**Comment by joakimnordlund** [comment]
![selfie-0](http://i.imgur.com/yiGlRfI.gif)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

I just got this issue.

**Comment by teoljungberg** [comment]
I opened #4 to resolve this issue, I'll release 2.0.1 shortly.

**Comment by teoljungberg** [comment]
v2.0.1 has been released, which resolves this issue.

Thanks for reporting this bug 🏩

**Comment by himynameisjonas** [comment]
Hm, the git author still doesn't change when I run git duo commands from a sub directory. I can list authors but setting the active pair doesn't work.

**Comment by teoljungberg** [comment]
@himynameisjonas Damn, new fix on the way!

**Comment by teoljungberg** [comment]
Thanks for your patience Jonas!

This is fixed and tested with:

```
% bundle exec ruby -S bin/git-duo --email "board+%names@gotham.travel"
% bundle exec ruby -S bin/git-duo --add "bruce Bruce Wayne <bruce@gotham.travel>"
% bundle exec ruby -S bin/git-duo --add "alfred Alfred Pennyworth <alfred@gotham.travel>"
% cd test
% bundle exec ruby -S ../bin/git-duo alfred bruce
% cd ..
```

And it works like a charm.

**Comment by teoljungberg** [comment]
v2.0.2 is shipped with this bug resolved, hopefully once and for all.
